apiVersion: v1
kind: Service
metadata:
  name: chatterbox-follower-service
spec:
  selector:
    app: chatterbox-follower-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
