server:
  port: 9095


spring:
  application:
    name: chatterbox-follower-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    follow-events-topic-name: chatterbox-follow-events
  redis:
    host: localhost
    port: 6379
    timeout: 60000

logging:
  level:
    com.chatterbox.followerservice: INFO
